import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {ColorSchemeScript, MantineProvider} from "@mantine/core";
import '@mantine/core/styles.css';
import MusicPlayer from "@/components/music/MusicPlayer";
import React from "react";
import {ContextProvider} from "@/app/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
          <head>
              <ColorSchemeScript/><title></title>
          </head>
          <body className={inter.className}>
          <MantineProvider>
              <ContextProvider>
                  {children}
                  <MusicPlayer/>
              </ContextProvider>
          </MantineProvider>
          </body>
      </html>
  );
}
